# Generated by Django 4.0.1 on 2023-11-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.CharField(default='URL_predeterminada', max_length=255),
        ),
    ]
