# Generated by Django 4.0 on 2023-11-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
